void directory_top_menu();
void directory_change_menu();
void function_key_menu();
void show_directory_input();
void sort_view();
void directory_view_menu_inputs0();
void directory_view_menu_inputs1();
void directory_change_menu_inputs();
void show_directory_inputs();
void copy_file_input(char *file);
void rename_file_input(char *file);
void make_directory_input();
void delete_file_confirm();
void delete_file_confirm_input(char *file);
